### ISSUE TITLE
Kadabra Moves broken lvl 16

### ISSUE THREAD

**Issue by Kvitekvist** [cRz-Shadows/Pokemon_Yellow_Legacy#1]
Kadabra learned: Psybeam, Recover, Psychicc, Reflect, Confusion
At the moment it evolved from Abra to Kadabra at lvl 16. This seems a bit unbalanced.

But also big plus that Abra spawns at lvl 13, only needing 3 levels to evolve, thanks for that! <3

**Comment by cRz-Shadows** [comment]
That bug is already fixed here, and a new patch will be released when some other bugs we're working on are fixed. It's worth reading the latest commit messages before making an issue in future.
