### ISSUE TITLE
Suggestion: More Following Pokemon

### ISSUE THREAD

**Issue by lukasz2224** [cRz-Shadows/Pokemon_Yellow_Legacy#3]
I suggest adding an ability to have a following Pokémon by pressing select when in party menu.
In battle, it would slide from the right to left instead of the usual poke ball release animation.

I know that Pokémon yellow was mainly focused on Pikachu, but the ability to have Pokémon following (other than Pikachu) would be very nice.

**Comment by cRz-Shadows** [comment]
I'll be honest, that's probably not going to happen. But you're welcome to make a fork and add them yourself.
