### ISSUE TITLE
Doesn't work on the native hardware (or backwards compatibility mode of my 3DS old) or even to my 3ds (GameYob Emulator) and PSP emulator (RIN Emulator).

### ISSUE THREAD

**Issue by Zushikina-kun** [cRz-Shadows/Pokemon_Yellow_Legacy#9]
For some reason, Pokemon Yellow Legacy won’t boot or run anymore after updating to version v1.0.10, just a white screen or straight up not working or not boot at all. 

v1.0.9 of Yellow Legacy and Pokemon Crystal Legacy v1.3.1 work fine.

I have tried running it on my PSP (RIN Emulator) and 3DS (GameYob Emulator), and it won’t boot—just a white screen. I have not tried playing them natively yet, like on hardware or GBa Firm (3DS backward compatibility), but from what I have seen from the comments, it does not work in native hardware so basically it might not work there as well.

Hardware used:
-PSP 1000
-3DS (old)

Software/Emulator used:
-GameYob 3DS
-RIN Emulator PSP
-3DS Native Backwards Compatibility Mode or Open_AGB_firm

**Comment by cRz-Shadows** [comment]
I have seen a large amount of community members as well as one of our testers run the game natively on GBC, additionally I have seen many community members run the game on 3DS. I am not sure which comments you are referring to. Additionally v1.0.10 was a pretty minor bugfix update which would not break that kind of compatability. This sounds more like a botched patch job than the update breaking compatability, I recommend you check your hashes as explained in any of the posts you can download the patch from https://github.com/cRz-Shadows/Pokemon_Yellow_Legacy/releases/tag/V1.0.10

**Comment by Zushikina-kun** [comment]
I'll try that

**Comment by Zushikina-kun** [comment]
It's working now, yep it's indeed a botch patching from this site: https://www.pokeharbor.com/2024/01/pokemon-crystal-legacy/

**Comment by Zushikina-kun** [comment]
thanks

**Comment by Zushikina-kun** [comment]
will do that, thanks again. that's what I did tbh, to also start playing Emerald Legacy as well (patched it myself as well ofc), best of luck, I was waiting for this one NGL!!
